# samtools, FastTree, and minimap2 not yet available on conda repositories as native arm64 binaries,
# so these need to be installed from source
#
# Additionally, install htslib from source, then run:
# export HTSLIB_LIBRARY_DIR=/path/to/htslib/lib
# export HTSLIB_INCLUDE_DIR=/path/to/htslib/include
# prior to running: conda env create -f environment_osx-arm64.yaml

name: covid-cg
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.8.8
  - numpy=1.20.2
  - scipy=1.6.2
  - pandas=1.2.5
  - pip=20.1.1
  - snakemake-minimal=5.20.1
  #- samtools=1.10
  - bs4=4.9.3
  - biopython=1.78
  #- fasttree=2.1.10
  - treetime=0.7.5
  - networkx=2.5.1
  - xlrd=2.0.1
  #- minimap2=2.21
  - scikit-learn=1.0
  - openblas=0.3.18
  - pip:
      - pysam==0.18.0
      # Email updates
      - sendgrid==6.0.5
  # For pushing to database
  - psycopg2==2.9.3
