const LOCAL_COUNTS = 'LOCAL_COUNTS';
const GLOBAL_COUNTS = 'GLOBAL_COUNTS';
const GROUP_COUNTS = 'GROUP_COUNTS';
export const LOW_FREQ_FILTER_TYPES = {
  LOCAL_COUNTS,
  GLOBAL_COUNTS,
  GROUP_COUNTS,
};

const GROUP_LINEAGE = 'GROUP_LINEAGE';
const GROUP_CLADE = 'GROUP_CLADE';
const GROUP_SNV = 'GROUP_SNV';
export const GROUP_KEYS = {
  GROUP_LINEAGE,
  GROUP_CLADE,
  GROUP_SNV,
};

const DNA = 'DNA';
const AA = 'AA';
export const DNA_OR_AA = {
  DNA,
  AA,
};

const COORD_GENE = 'COORD_GENE';
const COORD_PROTEIN = 'COORD_PROTEIN';
const COORD_PRIMER = 'COORD_PRIMER';
const COORD_CUSTOM = 'COORD_CUSTOM';
const COORD_SEQUENCE = 'COORD_SEQUENCE';
export const COORDINATE_MODES = {
  COORD_GENE,
  COORD_PROTEIN,
  COORD_PRIMER,
  COORD_CUSTOM,
  COORD_SEQUENCE,
};
