const DOWNLOAD_DATA = 'Plot Data';
const DOWNLOAD_PNG = 'PNG';
const DOWNLOAD_PNG_2X = 'PNG (2X)';
const DOWNLOAD_PNG_4X = 'PNG (4X)';
const DOWNLOAD_SVG = 'SVG';
export const PLOT_DOWNLOAD_OPTIONS = {
  DOWNLOAD_DATA,
  DOWNLOAD_PNG,
  DOWNLOAD_PNG_2X,
  DOWNLOAD_PNG_4X,
  DOWNLOAD_SVG,
};
