const NORM_COUNTS = 'counts';
const NORM_PERCENTAGES = 'percentages';
export const NORM_MODES = {
  NORM_COUNTS,
  NORM_PERCENTAGES,
};

const COUNT_NEW = 'new';
const COUNT_CUMULATIVE = 'cumulative';
export const COUNT_MODES = {
  COUNT_NEW,
  COUNT_CUMULATIVE,
};

const DATE_BIN_DAY = 'day';
const DATE_BIN_WEEK = 'week';
const DATE_BIN_MONTH = 'month';
export const DATE_BINS = {
  DATE_BIN_DAY,
  DATE_BIN_WEEK,
  DATE_BIN_MONTH,
};

const COLOR_MODE_COMPARE = 'compare';
const COLOR_MODE_CODE = 'code';
const COLOR_MODE_CLUSTAL = 'clustal';
const COLOR_MODE_ZAPPO = 'zappo';
const COLOR_MODE_ZHAO_LONDON = 'zhao_london';
export const COLOR_MODES = {
  COLOR_MODE_COMPARE,
  COLOR_MODE_CODE,
  COLOR_MODE_CLUSTAL,
  COLOR_MODE_ZAPPO,
  COLOR_MODE_ZHAO_LONDON,
};

const COMPARE_MODE_MATCH = 'match';
const COMPARE_MODE_MISMATCH = 'mismatch';
export const COMPARE_MODES = {
  COMPARE_MODE_MATCH,
  COMPARE_MODE_MISMATCH,
};

const COMPARE_COLOR_YELLOW = 'yellow';
const COMPARE_COLOR_GREEN = 'green';
const COMPARE_COLOR_BLUE = 'blue';
const COMPARE_COLOR_PINK = 'pink';
const COMPARE_COLOR_PURPLE = 'purple';
const COMPARE_COLOR_ORANGE = 'orange';
const COMPARE_COLOR_GRAY = 'gray';
const COMPARE_COLOR_DOTS = 'dots';
export const COMPARE_COLORS = {
  COLOR_MODE_CODE,
  COLOR_MODE_CLUSTAL,
  COLOR_MODE_ZAPPO,
  COLOR_MODE_ZHAO_LONDON,
  COMPARE_COLOR_YELLOW,
  COMPARE_COLOR_GREEN,
  COMPARE_COLOR_BLUE,
  COMPARE_COLOR_PINK,
  COMPARE_COLOR_PURPLE,
  COMPARE_COLOR_ORANGE,
  COMPARE_COLOR_GRAY,
  COMPARE_COLOR_DOTS,
};

const SORT_ASC = 'asc';
const SORT_DESC = 'desc';
const SORT_NONE = 'none';
export const SORT_DIRECTIONS = {
  SORT_ASC,
  SORT_DESC,
  SORT_NONE,
};
