# ------------------
#       GLOBAL
# ------------------

# Virus this config is written for
virus: "sars2"

# Path to folder with downloaded and processed data
# This path is relative to the project root
data_folder: "data_6month"

# Path to folder with genome information (reference.fasta, genes.json, proteins.json)
# This path is relative to the project root
static_data_folder: "static_data/sars2"

# Path to folder with data to use in development
# This path is relative to the project root
example_data_folder: "data"

# Database for this virus
postgres_db: "cg_gisaid_6month"

# ------------------
#       INGEST
# ------------------

# Number of genomes to load into memory before flushing to disk
chunk_size: 100000

# --------------------
#       ANALYSIS
# --------------------

# Don't process sequences prior to this date
# Leave empty to ignore
start_date_cutoff:
# Don't process sequences after this date
# Leave empty to ignore
end_date_cutoff:

# Don't process sequences after X days ago
# Leave empty to ignore
start_date_cutoff_days_ago: 180
# Don't process sequences prior to X days ago
# Leave empty to ignore
end_date_cutoff_days_ago:

segments: ["1"]

# Insertions or deletions with more than this difference in bases between the
# ref and the alt will be discarded (NT level only)
max_indel_length: 100

# Mutations with less than this number of global occurrences will be ignored
mutation_count_threshold: 3

# Threshold of prevalence to report a mutation as being a consensus
# mutation for a group (e.g., clade, lineage)
consensus_fraction: 0.9

# Threshold of prevalence to report a mutation as being associated
# with a group (e.g., clade, lineage)
min_reporting_fraction: 0.05

metadata_cols:
  host:
    title: "Host"
  gender:
    title: "Gender"
  patient_status:
    title: "Patient Status"
  passage:
    title: "Passage"
    disabled: true
  specimen:
    title: "Specimen"
  sequencing_tech:
    title: "Sequencing"
  assembly_method:
    title: "Assembly"
  comment_type:
    title: "Flag"
  authors:
    title: "Authors"
  originating_lab:
    title: "Originating lab"
  submitting_lab:
    title: "Submitting lab"
  # PANGO metadata
  conflict:
    title: "PANGO conflict"
  ambiguity_score:
    title: "PANGO ambiguity score"
  scorpio_call:
    title: "scorpio call"
  scorpio_support:
    title: "scorpio support"
  scorpio_conflict:
    title: "scorpio conflict"
  scorpio_notes:
    title: "scorpio notes"
  pangolin_is_designated:
    title: "PANGO is_designated"
  pangolin_qc_status:
    title: "PANGO QC status"
  pangolin_qc_notes:
    title: "PANGO QC notes"
  pangolin_note:
    title: "pangolin note"

group_cols:
  lineage:
    name: "lineage"
    title: "PANGO Lineage"
    description: ""
    link:
      title: "(Lineage Descriptions)"
      href: "https://cov-lineages.org/descriptions.html"
    show_collapse_options: true
  gisaid_lineage:
    name: "gisaid_lineage"
    title: "PANGO Lineage (GISAID)"
    description: "PANGO assignments from GISAID"
    link:
      title: "(Lineage Descriptions)"
      href: "https://cov-lineages.org/descriptions.html"
  clade:
    name: "clade"
    title: "Clade"
    description: "For more information about clade and lineage nomenclature, visit this:"
    link:
      title: "[GISAID note]"
      href: "https://www.gisaid.org/references/statements-clarifications/clade-and-lineage-nomenclature-aids-in-genomic-epidemiology-of-active-hcov-19-viruses/"
    show_collapse_options: false

# AZ report options
report_gene: "S"
report_group_col: "lineage"

# Surveillance plot options
# see: workflow_main/scripts/surveillance.py
surv_group_col: "lineage"
surv_period: "W"
surv_min_combo_count: 50
surv_min_single_count: 50
surv_start_date_days_ago: 90
surv_end_date_days_ago: 30

# ---------------
#    DATABASE
# ---------------

# Split mutation table partitions into periods of this length
# See: https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases
# 'M' month end frequency
# 'Y' year end frequency
mutation_partition_break: "M"

# ---------------
#     SERVER
# ---------------

# Require a login for accessing the website
# Users are provided to the app via. the "LOGINS" environment variable,
# which is structured as "user1:pass1,user2:pass2,..."
login_required: false

dev_hostname: "http://localhost:5001"
prod_hostname:
  - "https://covidcg.org"
  - "https://sars2.pathmut.org"
  - "https://sars2.gisaid.pathmut.org"

# ----------------------
#     VISUALIZATION
# ----------------------

site_title: "COVID CG"
data_provider: "GISAID"

# Default references for each subtype
default_references:
  SARS-CoV-2: WIV04

# Home page
show_home_banner: true
show_walkthroughs: true
show_surveillance: true
show_global_seq_plot: true

show_reports_tab: true
show_global_sequencing_tab: true
show_methods_tab: true
show_related_projects_tab: true

default_gene: S
default_protein: nsp12 - RdRp

min_date: "2019-12-01"

show_logos:
  GISAID: true
  GenBank: false

# Allow downloads of sequence metadata (before aggregation)
allow_metadata_download: false
# Allow downloads of raw genomes
allow_genome_download: false
