# ------------------
#       GLOBAL
# ------------------

# Virus this config is written for
virus: "sars2"

# Path to folder with downloaded and processed data
# This path is relative to the project root
data_folder: "data_genbank/sars2"

# Path to folder with genome information (reference.fasta, genes.json, proteins.json)
# This path is relative to the project root
static_data_folder: "static_data/sars2"

# Database for this virus
postgres_db: "cg_genbank"

# ------------------
#       INGEST
# ------------------

# Download sequences from GenBank (NCBI Virus vvsearch) in chunks of this size
# D = day, W = week, M = month, Y = year
dl_chunk_period: "W"

# Number of genomes to load into memory before flushing to disk
chunk_size: 100000

# --------------------
#       ANALYSIS
# --------------------

# Don't process sequences prior to this date
# Leave empty to ignore
start_date_cutoff:
# Don't process sequences after this date
# Leave empty to ignore
end_date_cutoff:

# Don't process sequences after X days ago
# Leave empty to ignore
start_date_cutoff_days_ago:
# Don't process sequences prior to X days ago
# Leave empty to ignore
end_date_cutoff_days_ago:

segments: ["1"]

# Insertions or deletions with more than this difference in bases between the
# ref and the alt will be discarded (NT level only)
max_indel_length: 100

# Mutations with less than this number of global occurrences will be ignored
mutation_count_threshold: 3

# Threshold of prevalence to report a mutation as being a consensus
# mutation for a group (e.g., clade, lineage)
consensus_fraction: 0.9

# Threshold of prevalence to report a mutation as being associated
# with a group (e.g., clade, lineage)
min_reporting_fraction: 0.05

metadata_cols:
  database:
    title: "Database"
  host:
    title: "Host"
  isolation_source:
    title: "Isolation source"
  authors:
    title: "Authors"
  publications:
    title: "Publications"

group_cols:
  lineage:
    name: "lineage"
    title: "Lineage"
    description: ""
    link:
      title: "(Lineage Descriptions)"
      href: "https://cov-lineages.org/descriptions.html"
    show_collapse_options: true

# AZ report options
report_gene: S
report_group_col: lineage

# Surveillance plot options
# see: workflow_main/scripts/surveillance.py
surv_group_col: "lineage"
surv_period: "W"
surv_min_combo_count: 50
surv_min_single_count: 50
surv_start_date: "2020-01-01" # Overrides days ago
# surv_start_date_days_ago: 90
surv_end_date: "2020-03-01" # Overrides days ago
# surv_end_date_days_ago: 30

# ---------------
#    DATABASE
# ---------------

# Split mutation table partitions into periods of this length
# See: https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases
# 'M' month end frequency
# 'Y' year end frequency
mutation_partition_break: "M"

# ---------------
#     SERVER
# ---------------

# Require a login for accessing the website
# Users are provided to the app via. the "LOGINS" environment variable,
# which is structured as "user1:pass1,user2:pass2,..."
login_required: false

dev_hostname: "http://localhost:5001"
prod_hostname:
  - "https://genbank.covidcg.org"
  - "https://sars2.genbank.pathmut.org"

# ----------------------
#     VISUALIZATION
# ----------------------

site_title: "COVID CG Genbank"
data_provider: "NCBI GenBank"
motd_url: "https://storage.googleapis.com/ve-public/MOTD_SARS2_GENBANK.html"

# Default references for each subtype
default_references:
  SARS-CoV-2: WIV04

# Home page
show_home_banner: false
show_walkthroughs: true
show_surveillance: true
show_global_seq_plot: false

show_reports_tab: false
show_global_sequencing_tab: false
show_methods_tab: false
show_related_projects_tab: false

default_gene: S
default_protein: nsp12 - RdRp

min_date: "2019-12-01"

show_logos:
  GISAID: false
  GenBank: true

# Allow downloads of sequence metadata (before aggregation)
allow_metadata_download: true
# Allow downloads of raw genomes
allow_genome_download: true
