# ------------------
#       GLOBAL
# ------------------

# Virus this config is written for
virus: "flu"

# Path to folder with downloaded and processed data
# This path is relative to the project root
data_folder: "data_flu_small"

# Path to folder with genome information (reference.fasta, genes.json, proteins.json)
# This path is relative to the project root
static_data_folder: "static_data/flu"

# Path to folder with data to use in development
# This path is relative to the project root
# Only used for database seeding in development
example_data_folder: "data_flu_small"

# Database for this virus
postgres_db: "flu_gisaid_dev"

# ------------------
#       INGEST
# ------------------

# Number of genomes to load into memory before flushing to disk
chunk_size: 10000

# --------------------
#       ANALYSIS
# --------------------

segments: ["1", "2", "3", "4", "5", "6", "7", "8"]

# Insertions or deletions with more than this difference in bases between the
# ref and the alt will be discarded (NT level only)
max_indel_length: 100

# Mutations with less than this number of global occurrences will be ignored
mutation_count_threshold: 3

# Threshold of prevalence to report a mutation as being a consensus
# mutation for a group (e.g., clade, lineage)
consensus_fraction: 0.9

# Threshold of prevalence to report a mutation as being associated
# with a group (e.g., clade, lineage)
min_reporting_fraction: 0.05

metadata_cols:
  passage:
    title: "Passage"
  host:
    title: "Host"
  isolate_submitter:
    title: "Isolate Submitter"
  submitting_lab:
    title: "Submitting Lab"
  originating_lab:
    title: "Originating Lab"
  authors:
    title: "Authors"
  publication:
    title: "Publication"
  gender:
    title: "Gender"
  patient_status:
    title: "Patient Status"

group_cols:
  serotype:
    name: "serotype"
    title: "Serotype"
    description: ""
    show_collapse_options: false

# AZ report options
report_gene: HA
report_group_col: serotype
report_group_references:
  B-vic: B-Austria-1359417-2021
  B-yam: B-Phuket-3073-2013
  H1N1: A-Wisconsin-67-2022
  H3N2: A-Darwin-6-2021

# Surveillance plot options
# see: workflow_main/scripts/surveillance.py
surv_group_col: "serotype"
surv_start_date: "1956-01-01"
surv_period: "Y"
surv_min_combo_count: 50
surv_min_single_count: 50
surv_start_date_days_ago: 90
surv_end_date_days_ago: 30
surv_group_references:
  B-vic: B-Austria-1359417-2021
  B-yam: B-Phuket-3073-2013
  H1N1: A-Wisconsin-67-2022
  H3N2: A-Darwin-6-2021

# ---------------
#    DATABASE
# ---------------

# Split mutation table partitions into periods of this length
# See: https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases
# Common options:
# 'D' calendar day frequency
# 'W' weekly frequency
# 'M' month end frequency
mutation_partition_break: "Y"

# ---------------
#     SERVER
# ---------------

# Require a login for accessing the website
# Users are provided to the app via. the "LOGINS" environment variable,
# which is structured as "user1:pass1,user2:pass2,..."
login_required: true

dev_hostname: "http://localhost:5003"
prod_hostname:
  - "https://flu.pathmut.org"
  - "https://flu.gisaid.pathmut.org"

# ----------------------
#     VISUALIZATION
# ----------------------

site_title: "Flu PathMut"
data_provider: "GISAID"

# Home page
show_home_banner: false
show_walkthroughs: false
show_surveillance: true
show_global_seq_plot: false

show_reports_tab: false
show_global_sequencing_tab: false
show_methods_tab: false
show_related_projects_tab: false

default_gene: HA
default_protein: HA

min_date: "1956-01-01"

show_logos:
  GISAID: true
  GenBank: false

# Allow downloads of sequence metadata (before aggregation)
allow_metadata_download: true
# Allow downloads of raw genomes
allow_genome_download: true
