# ------------------
#       GLOBAL
# ------------------

# Virus this config is written for
virus: "rsv"

# Path to folder with downloaded and processed data
# This path is relative to the project root
data_folder: "data_custom"

# Path to folder with genome information (reference.fasta, genes.json, proteins.json)
# This path is relative to the project root
static_data_folder: "static_data"

# Path to folder with data to use in development
# This path is relative to the project root
example_data_folder: "example_data_genbank"

# Database for this virus
postgres_db: "rsv_custom"

# ------------------
#       INGEST
# ------------------

# Number of genomes to load into memory before flushing to disk
chunk_size: 100000

# --------------------
#       ANALYSIS
# --------------------

# Don't process sequences prior to this date
# Leave empty to ignore
start_date_cutoff:
# Don't process sequences after this date
# Leave empty to ignore
end_date_cutoff:

# Don't process sequences after X days ago
# Leave empty to ignore
start_date_cutoff_days_ago:
# Don't process sequences prior to X days ago
# Leave empty to ignore
end_date_cutoff_days_ago:

segments: ["1"]

# Insertions or deletions with more than this difference in bases between the
# ref and the alt will be discarded (NT level only)
max_indel_length: 100

# Mutations with less than this number of global occurrences will be ignored
mutation_count_threshold: 3

# Threshold of prevalence to report a mutation as being a consensus
# mutation for a group (e.g., clade, lineage)
consensus_fraction: 0.9

# Threshold of prevalence to report a mutation as being associated
# with a group (e.g., clade, lineage)
min_reporting_fraction: 0.05

metadata_cols:
  host:
    title: "Host"

group_cols:
  subtype:
    name: "subtype"
    title: "Subtype"
    description: ""
    show_collapse_options: false
  genotype:
    name: "genotype"
    title: "Genotype"
    description: ""
    show_collapse_options: false

# AZ report options
report_gene: F
report_group_col: subtype
report_group_references:
  A: KX858757.1
  B: KX858756.1

# Surveillance plot options
# see: workflow_main/scripts/surveillance.py
surv_group_col: "subtype"
surv_start_date: "1956-01-01"
surv_period: "Y"
surv_min_combo_count: 50
surv_min_single_count: 50
surv_start_date_days_ago: 90
surv_end_date_days_ago: 30
surv_group_references:
  A: KX858757.1
  B: KX858756.1

# ---------------
#    DATABASE
# ---------------

# Split mutation table partitions into periods of this length
# See: https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases
# Common options:
# 'D' calendar day frequency
# 'W' weekly frequency
# 'M' month end frequency
mutation_partition_break: "Y"

# ---------------
#     SERVER
# ---------------

# Require a login for accessing the website
# Users are provided to the app via. the "LOGINS" environment variable,
# which is structured as "user1:pass1,user2:pass2,..."
login_required: false

dev_hostname: "http://localhost:5002"
prod_hostname:
  - "http://localhost:8080"

# ----------------------
#     VISUALIZATION
# ----------------------

site_title: "RSV PathMut"
data_provider: "Custom"

# Default references for each subtype
default_references:
  A: KX858757.1
  B: KX858756.1

# Home page
show_home_banner: false
show_walkthroughs: false
show_surveillance: true
show_global_seq_plot: false

show_reports_tab: false
show_global_sequencing_tab: false
show_methods_tab: false
show_related_projects_tab: false

default_gene: F
default_protein: F

min_date: "1956-01-01"

show_logos:
  GISAID: false
  GenBank: true

# Allow downloads of sequence metadata (before aggregation)
allow_metadata_download: true
# Allow downloads of raw genomes
allow_genome_download: true
