# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Sentry Release
        # You may pin to the exact commit or the version.
        # uses: getsentry/action-release@641a80f3e05619b174bcacbfa3b69dff382d2a33
        uses: getsentry/action-release@v1.1.5
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          # Set the environment for this release. E.g. "production" or "staging". Omit to skip adding deploy to release.
          environment: production
          # Space-separated list of paths to JavaScript sourcemaps. Omit to skip uploading sourcemaps.
          #sourcemaps: # optional
          # When false, omit marking the release as finalized and released.
          #finalize: # optional, default is true
          # Unix timestamp of the release start date. Omit for current time.
          #started_at: # optional
          # Identifier that uniquely identifies the releases. Omit to auto-generate one.
          #version: # optional
          # Value prepended to auto-generated version.
          #version_prefix: # optional
          # Specify whether to set commits for the release. Either "auto" or "skip".
          #set_commits: # optional
          # Space-separated list of projects. Defaults to the env variable "SENTRY_PROJECT" if not provided.
          #projects: # optional
          # Adds a prefix to source map urls after stripping them.
          #url_prefix: # optional
